let openbtn =document.getElementById('open-btn');
console.log(openbtn);
let nameshop =document.getElementsByClassName('name-value')[0];
console.log(nameshop);
let budget =document.getElementsByClassName('budget-value')[0];
console.log(budget);
let goods =document.getElementsByClassName('goods-value')[0];
console.log(goods);
let  items =document.getElementsByClassName('items-value')[0];
console.log(items);
let employers =document.getElementsByClassName('employers-value')[0];
console.log(employers);
let  discount =document.getElementsByClassName('discount-value')[0];
console.log(discount);
let isopen =document.getElementsByClassName('isopen-value')[0];
console.log(isopen);
let goodsitem=document.getElementsByClassName('goods-item');
console.log(goodsitem);
let btn =document.getElementsByTagName('button');
console.log(btn);
let chooseitem=document.querySelector('.chooseitem');
console.log(chooseitem);
let timevalue=document.querySelector('.time-value');
console.log(timevalue);
let countbudgetvalue=document.querySelector('.count-budget-value');
console.log(countbudgetvalue);
let emp=document.querySelectorAll('.hire-employers-item');
console.log(emp);
